---

- name: remove existing ecsbeat container
  ignore_errors: yes
  command: docker rm -f "{{ ecsbeat.container_name }}"

- name: start docker container
  ignore_errors: yes
  command: |
    docker run -d
               --pid=host
               --net=host
               --memory="128m"
               --name "{{ ecsbeat.container_name }}"
               -v "{{ destdir }}/{{ ecsbeat.config_dir }}/{{ ecsbeat.config_file }}:/ecsbeat/ecsbeat.yml"
               -e LOGSTASH_HOSTS='{{ output.logstash.hosts }}'
               -e ECS_HOSTS='{{ ECS.hosts }}'
               -e ECS_USERNAME='{{ ECS.username }}'
               -e ECS_PASSWORD='{{ ECS.password }}'
               "{{ images.ecsbeat.image }}"

