---

- name: remove existing ecsbeat container
  ignore_errors: yes
  command: docker rm -f "{{ ecsbeat.container_name }}"

- name: start docker container
  command: |
    docker run -d
               --pid=host
               --net=host
               --memory="128m"
               --log-opt max-size="{{ log_size }}"
               --restart=always
               --name "{{ ecsbeat.container_name }}"
               -v "{{ destdir }}/{{ ecsbeat.config_dir }}/{{ ecsbeat.config_file }}:/ecsbeat/ecsbeat.yml"
               -e LOGSTASH_HOSTS='{{ output.logstash.hosts }}'
               -e ECS_HOSTS='{{ ecs_hosts }}'
               -e ECS_USERNAME='{{ ecs_username }}'
               -e ECS_PASSWORD='{{ ecs_password }}'
               "{{ images.ecsbeat.image }}"

