
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    -
      paths:
        - /opt/emc/caspian/fabric/agent/services/object/main/log/messages
      input_type: log
      document_type: restart

    -
      paths:
        - /opt/emc/caspian/fabric/agent/services/object/main/log/dataheadsvc.log
      input_type: log
      document_type: dataheadsvc
      tail_files: true
      multiline:
        pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
        negate: true
        match: after

    - 
      paths:
        - /opt/emc/caspian/fabric/agent/services/object/main/log/*-gc-*.log.0.current
      tail_files: true
      document_type: svcgclog
      multiline:
        pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
        negate: true
        match: after
      
    -
      paths:
        - /opt/emc/caspian/fabric/agent/services/object/main/log/vnest-perf-counter.log
      tail_files: true
      document_type: perfcounterlog
      include_lines:
        - 'vNest.getKV'
        - 'vNest.listKV'
        - 'vNest.insertKV'
        - 'vNest.insertKVIfAbsent'
        - 'vNest.batchExecKV'
        - 'vNest.removeKV'
        - 'BTree.getPageFromDisk'
        - 'Chunk.journalWrite'

    -
      paths:
        - /opt/emc/caspian/fabric/agent/services/object/main/log/vnest.log
      tail_files: true
      document_type: javalog
      multiline:
        pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
        negate: true
        match: after
      include_lines:
        - 'BTree stats PageManager CacheStats'
        - 'successfully dump'
        - 'key in transition'
        - 'Wait for write completion timed out'
        - 'send UpdateGroupMembershipRequest'
        - 'HeartBeatMonitor.*node'

#    -
#      paths:
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/btree-gc.log
#      tail_files: true
#      document_type: btreegclog
#      multiline:
#        pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
#        negate: true
#        match: after
#      include_lines: ['Total unserialized size of the tree']
#
#    -
#      paths:
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/dataheadsvc-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/blobsvc-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/georeceiver-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/ssm-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/btree-gc-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/metering-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/stat-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/cm-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/nginx_error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/storageserver-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/provisionsvc-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/transformsvc-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/dtquery-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/resourcesvc-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/eventsvc-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/rm-error.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/vnest-error.log
#      tail_files: true
#      max_bytes: 32700
#      document_type: svcerrorlog
#      multiline:
#        pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
#        negate: true
#        match: after
#
#    -
#      paths:
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/blobsvc-chunk-lifecycle.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/cm-chunk-lifecycle.log
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/metering-chunk-lifecycle.log
#      tail_files: true
#      document_type: chunklifelog
#      multiline:
#        pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
#        negate: true
#        match: after
#
#    -
#      paths:
#        - /opt/emc/caspian/fabric/agent/services/object/main/log/blobsvc.log
#      tail_files: true
#      document_type: blobsvclog
#      multiline:
#        pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
#        negate: true
#        match: after


fields_under_root: true
fields:
   ecs-node-ip: ${ECS_NODE_IP}
   ecs-vdc-name: ${ECS_VDC_NAME}
   ecs-vdc-id: ${ECS_VDC_ID}

output:

  ### Logstash as output
  logstash:
    # The Logstash hosts
    #hosts: ["localhost:5044"]
    hosts: [LOGSTASH_HOSTS]
