
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    -
      paths:
        - /opt/emc/caspian/fabric/agent/services/object/main/log/messages
      input_type: log
      document_type: restart

    -
      paths:
        - /opt/emc/caspian/fabric/agent/services/object/main/log/dataheadsvc.log

      input_type: log
      document_type: dataheadsvc
      tail_files: true
      multiline:
        pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
        negate: true
        match: after

fields_under_root: true
fields:
   ecs-node-ip: ${ECS_NODE_IP}

output:

  ### Logstash as output
  logstash:
    # The Logstash hosts
    #hosts: ["localhost:5044"]
    hosts: [LOGSTASH_HOSTS]
