
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    -
      paths:
        - /opt/emc/caspian/fabric/agent/services/object/main/log/messages
      input_type: log
      document_type: restart

    # access log for 3.1+
    #-
    #  paths:
    #    - /opt/emc/caspian/fabric/agent/services/object/main/log/dataheadsvc-access.log
    #  input_type: log
    #  document_type: datahead_access
    #  tail_files: true
    #  multiline:
    #    pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
    #    negate: true
    #    match: after

    # access log for 3.0x
    -
      paths:
        - /opt/emc/caspian/fabric/agent/services/object/main/log/dataheadsvc.log
      input_type: log
      document_type: dataheadsvc
      tail_files: true
      multiline:
        pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
        negate: true
        match: after
      include_lines: ['RequestLog']

fields_under_root: true
fields:
   ecs-node-ip: ${ECS_NODE_IP}
   ecs-vdc-name: ${ECS_VDC_NAME}
   ecs-vdc-id: ${ECS_VDC_ID}

output:

  ### Logstash as output
  logstash:
    # The Logstash hosts
    #hosts: ["localhost:5044"]
    hosts: [LOGSTASH_HOSTS]
